spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect